packages:
  - packages/*

catalog:
  '@antv/g-webgpu': ^2.1.1
  '@hypernym/nuxt-gsap': ^2.4.3
  '@iconify-json/mdi': ^1.2.3
  '@iconify-json/ph': ^1.2.2
  '@nuxt/eslint': ^1.15.2
  '@nuxt/fonts': ^0.14.0
  '@nuxt/icon': 2.2.1
  '@nuxt/image': ^2.0.0
  '@types/d3': ^7.4.3
  '@types/lodash': ^4.17.24
  '@unocss/nuxt': ^66.6.2
  '@unocss/reset': ^66.6.2
  '@vueuse/core': 14.2.1
  '@vueuse/motion': ^3.0.3
  '@vueuse/nuxt': ^14.2.1
  '@webgpu/types': ^0.1.69
  async-wait-until: ^2.0.31
  bignumber.js: ^10.0.2
  chart.js: ^4.5.1
  d3: ^7.9.0
  eslint: ^10.0.2
  fraction.js: ^5.3.4
  gpu.js: ^2.16.0
  gsap: ^3.14.2
  katex: ^0.16.33
  lodash: ^4.17.23
  math-expression-evaluator: ^2.0.7
  nuxt: 4.3.1
  sass-embedded: ^1.97.3
  tone: 15.5.3
  unocss: ^66.6.2
  vite: ^7.3.1
  vue: ^3.5.29
  vue-router: 5.0.3

onlyBuiltDependencies:
  - '@parcel/watcher'
  - esbuild
  - sharp
  - unrs-resolver
